name: "bazel"

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# Cancel any preceding run on the pull request.
concurrency:
  group: bazel-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

jobs:
  build_direct:  # Build p4c directly.
    runs-on: ubuntu-latest
    env:
      BAZEL: bazelisk-linux-amd64
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Cache Bazel
      uses: actions/cache@v3
      with:
        path: |
          ~/.cache/bazel
        key: ${{ runner.os }}-bazel-build-direct-${{ hashFiles('.bazelversion', '.bazelrc', 'WORKSPACE', 'WORKSPACE.bazel', 'MODULE.bazel') }}
        restore-keys: |
          ${{ runner.os }}-bazel-build-direct-

    - name: First, pass the lint test
      run: bazel run //:buildifier_check

    - name: Install Flex and Bison
      run: sudo apt-get update && sudo apt-get install bison flex libfl-dev

    - name: Build p4c
      run: bazel build //... --verbose_failures

  build_indirect:  # Build 3rd party Bazel project depending on p4c as a subproject.
    runs-on: ubuntu-latest
    env:
      BAZEL: bazelisk-linux-amd64
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Cache Bazel
      uses: actions/cache@v3
      with:
        path: |
          ~/.cache/bazel
        key: ${{ runner.os }}-bazel-build-indirect-${{ hashFiles('.bazelversion', '.bazelrc', 'WORKSPACE', 'WORKSPACE.bazel', 'MODULE.bazel') }}
        restore-keys: |
          ${{ runner.os }}-bazel-build-indirect-

    - name: First, pass the lint test
      run: bazel run //:buildifier_check

    - name: Install Flex and Bison
      run: sudo apt-get update && sudo apt-get install bison flex libfl-dev

    - name: Build bazel/example
      run: cd ./bazel/example && bazel build //... --verbose_failures
